"""Wavefront OBJ writer with an accompanying MTL and texture map.

OBJ is the format the Roblox 3D Importer handles most predictably, so this
writer is the primary path for that target. Roblox reads UVs and the texture
referenced by the MTL; it ignores per-vertex colour, which is only emitted when
the caller asks for it.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np

from ..errors import ExportError
from ..imaging import save_image
from ..types import Mesh

__all__ = ["write_obj"]


def write_obj(
    mesh: Mesh,
    path: str | os.PathLike,
    texture: np.ndarray | None = None,
    include_vertex_colors: bool = False,
    material_name: str = "material_0",
    **_: object,
) -> list[Path]:
    """Write ``mesh`` as ``.obj``, plus ``.mtl`` and a ``.png`` when textured.

    Returns every file written, OBJ first.
    """
    if mesh.is_empty:
        raise ExportError("Cannot export an empty mesh to OBJ")

    obj_path = Path(path)
    obj_path.parent.mkdir(parents=True, exist_ok=True)
    written = [obj_path]

    has_uvs = mesh.uvs is not None
    has_normals = mesh.vertex_normals is not None
    write_texture = texture is not None and has_uvs

    mtl_path = obj_path.with_suffix(".mtl")
    texture_path = obj_path.with_name(f"{obj_path.stem}_texture.png")

    lines: list[str] = [
        "# Wavefront OBJ generated by image-to-model",
        f"# {mesh.n_vertices} vertices, {mesh.n_faces} triangles",
    ]
    if write_texture or has_uvs:
        lines.append(f"mtllib {mtl_path.name}")

    # Positions, optionally with the non-standard but widely read r/g/b suffix.
    if include_vertex_colors and mesh.vertex_colors is not None:
        colors = mesh.vertex_colors.astype(np.float32) / 255.0
        for (x, y, z), (r, g, b) in zip(mesh.vertices, colors):
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f} {r:.4f} {g:.4f} {b:.4f}")
    else:
        for x, y, z in mesh.vertices:
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")

    if has_uvs:
        # OBJ puts the texture origin at the bottom-left, glTF at the top-left,
        # so V is flipped on the way out.
        for u, v in mesh.uvs:
            lines.append(f"vt {u:.6f} {1.0 - v:.6f}")

    if has_normals:
        for nx, ny, nz in mesh.vertex_normals:
            lines.append(f"vn {nx:.6f} {ny:.6f} {nz:.6f}")

    if write_texture or has_uvs:
        lines.append(f"usemtl {material_name}")
    lines.append("s 1")

    # OBJ indices are 1-based and share one index per element triple here,
    # since positions, UVs and normals are all per-vertex.
    faces = mesh.faces + 1
    if has_uvs and has_normals:
        fmt = "f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}"
    elif has_uvs:
        fmt = "f {0}/{0} {1}/{1} {2}/{2}"
    elif has_normals:
        fmt = "f {0}//{0} {1}//{1} {2}//{2}"
    else:
        fmt = "f {0} {1} {2}"
    lines.extend(fmt.format(a, b, c) for a, b, c in faces)

    obj_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if write_texture or has_uvs:
        mtl_lines = [
            "# generated by image-to-model",
            f"newmtl {material_name}",
            "Ka 1.000 1.000 1.000",
            "Kd 1.000 1.000 1.000",
            "Ks 0.000 0.000 0.000",
            "d 1.0",
            "illum 1",
        ]
        if write_texture:
            mtl_lines.append(f"map_Kd {texture_path.name}")
        mtl_path.write_text("\n".join(mtl_lines) + "\n", encoding="utf-8")
        written.append(mtl_path)

    if write_texture:
        save_image(texture, texture_path)
        written.append(texture_path)

    return written
